import { db } from "./db";
import { products } from "@shared/schema";
import type { InsertProduct } from "@shared/schema";

const initialProducts: InsertProduct[] = [
  // Rust MEK variants
  {
    name: "Rust MEK - 1 Day",
    description: "Premium Rust enhancement tool - 1 Day access",
    price: "7.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 15,
    inStock: true,
    imageUrl: "/attached_assets/rust-mek-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-mek-1day.zip",
    licenseKey: "RUST-MEK-1D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust MEK - 3 Day",
    description: "Premium Rust enhancement tool - 3 Day access",
    price: "15.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 12,
    inStock: true,
    imageUrl: "/attached_assets/rust-mek-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-mek-3day.zip",
    licenseKey: "RUST-MEK-3D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust MEK - 7 Day",
    description: "Premium Rust enhancement tool - 7 Day access",
    price: "29.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 8,
    inStock: true,
    imageUrl: "/attached_assets/rust-mek-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-mek-7day.zip",
    licenseKey: "RUST-MEK-7D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust MEK - 30 Day",
    description: "Premium Rust enhancement tool - 30 Day access",
    price: "59.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 5,
    inStock: true,
    imageUrl: "/attached_assets/rust-mek-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-mek-30day.zip",
    licenseKey: "RUST-MEK-30D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust MEK - Lifetime",
    description: "Premium Rust enhancement tool - Lifetime access",
    price: "249.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 2,
    inStock: true,
    imageUrl: "/attached_assets/rust-mek-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-mek-lifetime.zip",
    licenseKey: "RUST-MEK-LT-XXXX",
    deliveryType: "download",
  },
  // Temp Spoofer variants
  {
    name: "Temp Spoofer - 1 Day",
    description: "Temporary hardware ID spoofer - 1 Day access",
    price: "5.99",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 20,
    inStock: true,
    imageUrl: "/attached_assets/temp-spoofer-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/temp-spoofer-1day.zip",
    licenseKey: "TSPOOF-1D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Temp Spoofer - 7 Day",
    description: "Temporary hardware ID spoofer - 7 Day access",
    price: "17.99",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 15,
    inStock: true,
    imageUrl: "/attached_assets/temp-spoofer-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/temp-spoofer-7day.zip",
    licenseKey: "TSPOOF-7D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Temp Spoofer - 30 Day",
    description: "Temporary hardware ID spoofer - 30 Day access",
    price: "36.99",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 10,
    inStock: true,
    imageUrl: "/attached_assets/temp-spoofer-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/temp-spoofer-30day.zip",
    licenseKey: "TSPOOF-30D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Temp Spoofer - Lifetime",
    description: "Temporary hardware ID spoofer - Lifetime access",
    price: "179.99",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 3,
    inStock: true,
    imageUrl: "/attached_assets/temp-spoofer-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/temp-spoofer-lifetime.zip",
    licenseKey: "TSPOOF-LT-XXXX",
    deliveryType: "download",
  },
  // Rust FA
  {
    name: "Rust FA",
    description: "Rust Full Access account with premium features",
    price: "7.99",
    originalPrice: null,
    category: "Game Accounts",
    game: "Rust",
    stockQuantity: 8,
    inStock: true,
    imageUrl: "/attached_assets/rust-fa-image.png",
    deliveryUrl: null,
    licenseKey: null,
    deliveryType: "account",
  },
  // Apex External variants
  {
    name: "Apex External - 1 Day",
    description: "External Apex Legends cheat - 1 Day access",
    price: "2.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Apex Legends",
    stockQuantity: 25,
    inStock: true,
    imageUrl: "/attached_assets/apex-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/apex-ext-1day.zip",
    licenseKey: "APEX-EXT-1D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Apex External - 3 Day",
    description: "External Apex Legends cheat - 3 Day access",
    price: "4.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Apex Legends",
    stockQuantity: 20,
    inStock: true,
    imageUrl: "/attached_assets/apex-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/apex-ext-3day.zip",
    licenseKey: "APEX-EXT-3D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Apex External - 7 Day",
    description: "External Apex Legends cheat - 7 Day access",
    price: "14.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Apex Legends",
    stockQuantity: 15,
    inStock: true,
    imageUrl: "/attached_assets/apex-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/apex-ext-7day.zip",
    licenseKey: "APEX-EXT-7D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Apex External - 30 Day",
    description: "External Apex Legends cheat - 30 Day access",
    price: "29.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Apex Legends",
    stockQuantity: 8,
    inStock: true,
    imageUrl: "/attached_assets/apex-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/apex-ext-30day.zip",
    licenseKey: "APEX-EXT-30D-XXXX",
    deliveryType: "download",
  },
  // Perm Spoofer variants
  {
    name: "Perm Spoofer - One Time",
    description: "Permanent hardware ID spoofer - One time use",
    price: "21.00",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 12,
    inStock: true,
    imageUrl: "/attached_assets/perm-spoofer-fresh.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/perm-spoofer-onetime.zip",
    licenseKey: "PSPOOF-OT-XXXX",
    deliveryType: "download",
  },
  {
    name: "Perm Spoofer - Lifetime",
    description: "Permanent hardware ID spoofer - Lifetime access",
    price: "55.00",
    originalPrice: null,
    category: "Spoofers",
    game: "Multi-Game",
    stockQuantity: 5,
    inStock: true,
    imageUrl: "/attached_assets/perm-spoofer-fresh.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/perm-spoofer-lifetime.zip",
    licenseKey: "PSPOOF-LT-XXXX",
    deliveryType: "download",
  },
  // Rust NFA
  {
    name: "Rust NFA 0-5000 hours",
    description: "Rust No Full Access account with 0-5000 hours playtime",
    price: "3.99",
    originalPrice: null,
    category: "Game Accounts",
    game: "Rust",
    stockQuantity: 30,
    inStock: true,
    imageUrl: "/attached_assets/rust-nfa-image.png",
    deliveryUrl: null,
    licenseKey: null,
    deliveryType: "account",
  },
  // Rust External variants
  {
    name: "Rust External - 1 Day",
    description: "External Rust cheat - 1 Day access",
    price: "5.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 18,
    inStock: true,
    imageUrl: "/attached_assets/rust-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-ext-1day.zip",
    licenseKey: "RUST-EXT-1D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust External - 3 Days",
    description: "External Rust cheat - 3 Days access",
    price: "9.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 14,
    inStock: true,
    imageUrl: "/attached_assets/rust-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-ext-3days.zip",
    licenseKey: "RUST-EXT-3D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust External - 7 Days",
    description: "External Rust cheat - 7 Days access",
    price: "21.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 10,
    inStock: true,
    imageUrl: "/attached_assets/rust-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-ext-7days.zip",
    licenseKey: "RUST-EXT-7D-XXXX",
    deliveryType: "download",
  },
  {
    name: "Rust External - 30 Day",
    description: "External Rust cheat - 30 Day access",
    price: "51.99",
    originalPrice: null,
    category: "Game Cheats",
    game: "Rust",
    stockQuantity: 6,
    inStock: true,
    imageUrl: "/attached_assets/rust-external-image.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/rust-ext-30day.zip",
    licenseKey: "RUST-EXT-30D-XXXX",
    deliveryType: "download",
  },
  // DMA Products
  {
    name: "DMA Bundle Firmware Included",
    description: "Complete DMA hardware bundle with firmware included for multi-game support",
    price: "659.99",
    originalPrice: null,
    category: "DMA Hardware",
    game: "Multi-Game",
    stockQuantity: 2,
    inStock: true,
    imageUrl: "https://i.postimg.cc/jjCxmnSp/Screenshot-2025-09-13-150454.png",
    deliveryUrl: "https://secure.pdcheats.uk/downloads/dma-bundle.zip",
    licenseKey: "DMA-BUNDLE-2025-XXXX",
    deliveryType: "download",
  },
];

async function seedDatabase() {
  try {
    console.log("🌱 Seeding database with initial products...");
    
    // Clear existing products first
    await db.delete(products);
    
    // Insert new products
    await db.insert(products).values(initialProducts);
    
    console.log(`✅ Successfully seeded ${initialProducts.length} products!`);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    throw error;
  }
}

// Run seeding if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase().then(() => process.exit(0));
}

export { seedDatabase };